export const getAvatars = [
  "/avatars/1.png",
  "/avatars/2.png",
  "/avatars/3.png",
  "/avatars/4.png",
  "/avatars/5.png",
  "/avatars/6.png",
  "/avatars/7.png",
  "/avatars/8.png",
  "/avatars/9.png",
  "/avatars/10.png",
  "/avatars/11.png",
  "/avatars/12.png",
  "/avatars/13.png",
  "/avatars/14.png",
  "/avatars/15.png",
];
