name: CI/CD Pipeline

on:
  pull_request: 
    branches: [develop]
  push: 
    branches: [develop]
    
jobs:
  avoid_reduncy: 
    runs-on: ubuntu-latest
    steps:
      - name: Cancel previous redundant build
        uses: styfle/cancel-workflow-action@0.9.1
        with: 
          access_token: ${{ github.token }}  
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Install pnpm 
        run: npm i -g pnpm@7

      - name: Server - Install dependencies
        run: pnpm i --no-frozen-lockfile
        working-directory: ./server
      
      - name: Server - Start
        run: pnpm run dev &
        working-directory: ./server

      - name: Wait for server to be ready
        run: sleep 10 

      - name: Client - Install dependencies
        run: pnpm i

      - name: Client - Start
        run: pnpm run dev &
       
      - name: Wait for client to be ready
        run: sleep 10 

      - name: Run Cypress Tests
        run: npm run test:all